_BASE_: baseline_config.yaml
DATASETS:
  TRAIN: ("stow_tabletop_syn_train",)
  TEST: ("stow_tabletop_real_val",)
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.00001
  STEPS: (14000, )
  MAX_ITER: 16000
  BACKBONE_MULTIPLIER: 0.1
  WARMUP_FACTOR: 0.1
  WARMUP_ITERS: 300
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0
MODEL:
  WEIGHTS: "./datasets/cache/model_final_94dc52_frame.pkl"
  META_ARCHITECTURE: "FrameMaskFormer"
  REID:
    ENCODER_TYPE: "linear"
    REID_NORMALIZE: True
    ENCODER_POS_TYPE: 'learned'
    # ENCODER_ONE_LAYER_AFTER_ATTENTION: True
    ENCODER_LAST_LAYER_BIAS: False
    # ENCODER_NUM_LAYERS: 3
    ENCODER_LAYER_STRUCTURE: ['cross', 'self', 'ffn', 'frame']
    # ENCODER_UPDATE_CONFIDENCE: True
    ENCODER_NORMALIZE_BEFORE: False
  SEM_SEG_HEAD:
    NAME: "FrameMaskFormerHead"
    IGNORE_VALUE: 255
    NUM_CLASSES: 1
    LOSS_WEIGHT: 1.0
    CONVS_DIM: 256
    MASK_DIM: 256
    NORM: "GN"
    # pixel decoder
    PIXEL_DECODER_NAME: "MSDeformAttnPixelDecoder"
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
    DEFORMABLE_TRANSFORMER_ENCODER_IN_FEATURES: ["res3", "res4", "res5"]
    COMMON_STRIDE: 4
    TRANSFORMER_ENC_LAYERS: 6
  MASK_FORMER:
    REID_SOFTMAX_TEMPERATURE: 0.07
    IGNORE_IOU_RANGE: [0.5, 0.999]
    MAX_NUM_BG: 25
    IGNORE_FIRST_OUTPUT: True
    CONTRASTIVE_ALPHA: 0.02
    CONTRASTIVE_SIGMA: 0.5
    TRANSFORMER_DECODER_NAME: "SequenceMultiScaleMaskedTransformerDecoder"
    TRANSFORMER_IN_FEATURE: "multi_scale_pixel_decoder"
    DEEP_SUPERVISION: True
    NO_OBJECT_WEIGHT: 0.1
    CLASS_WEIGHT: 2.0
    MASK_WEIGHT: 5.0
    DICE_WEIGHT: 5.0
    HIDDEN_DIM: 256
    NUM_OBJECT_QUERIES: 100
    NHEADS: 8
    DROPOUT: 0.0
    DIM_FEEDFORWARD: 2048
    ENC_LAYERS: 0
    PRE_NORM: False
    ENFORCE_INPUT_PROJ: False
    SIZE_DIVISIBILITY: 32
    DEC_LAYERS: 10  # 9 decoder layers, add one for the loss on learnable query
    TRAIN_NUM_POINTS: 12544
    OVERSAMPLE_RATIO: 3.0
    IMPORTANCE_SAMPLE_RATIO: 0.75
    # query from last frame
    MEMORY_FORWARD_STRATEGY: 'none'
    TRACK_POS_TYPE: 'zero'
    TRACK_FEAT_TYPE: 'memory'
    # dim for unique
    REID_DIM: 256
    REID_CONTRA_WEIGHT: 1.0
    REID_SOFTMAX_WEIGHT: 0.1
    REID_COEFF: 0.
    INV_REID_COEFF: 0.
    REID_LOSS_OVER: 'all'
    REID_FRAME_LOSS_TYPE: 'contrastive_cosdist+softmax'
    TEST:
      SEMANTIC_ON: False
      INSTANCE_ON: True
      PANOPTIC_ON: False
      OVERLAP_THRESHOLD: 0.8
      OBJECT_MASK_THRESHOLD: 0.8
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 16
INPUT:
  IMAGE_SIZE: 256
  MIN_SCALE: 0.1
  MAX_SCALE: 2.0
  FORMAT: "RGB"
  DATASET_MAPPER_NAME: "amazon_syn_v0"
  MIN_SIZE_TRAIN: (512,)
  MAX_SIZE_TRAIN: 512
  MIN_SIZE_TEST: 512
  MAX_SIZE_TEST: 512
  SAMPLING_FRAME_NUM: 4
  AUGMENTATIONS: ["brightness", "contrast", "saturation", "rotation"]